# Generated by Django 3.2.5 on 2021-10-06 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('rank', models.CharField(blank=True, max_length=3, null=True)),
                ('verified', models.CharField(blank=True, max_length=30, null=True)),
                ('creator', models.BooleanField(blank=True, default=False, null=True)),
                ('supersuer', models.BooleanField(blank=True, default=False, null=True)),
                ('password', models.CharField(max_length=30)),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('staff', models.BooleanField(blank=True, default=False, null=True)),
                ('prostaff', models.BooleanField(blank=True, default=False, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('api_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time', models.DateField()),
                ('name', models.TextField()),
                ('pid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.TextField()),
                ('time', models.DateField()),
            ],
        ),
    ]
